title: Clara NK 
description: Physics and computational projects
url: "https://nk-clara.github.io"
baseurl: "/nk-clara"

markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:name/
